### ISSUE TITLE
Add DAL and Devices Newsletter signup 

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/dev-docs#115]
The [DAL, Editors and devices mailing list signup](https://microbit.us14.list-manage.com/subscribe?u=e1c30f24b90ff3d70275cfff2&id=25403c7650) is currently a bit hidden away in the KB and we’ve only referred to it as part of the motion sensor change so far. https://support.microbit.org/en/support/solutions/articles/19000087020-micro-bit-motion-sensor-hardware-change

We should update the page here https://tech.microbit.org/get-involved/where-to-find/ with information on this list and a button to signup

Review link: http://dal-and-devices.review.tech.microbit.org.s3-website-eu-west-1.amazonaws.com/get-involved/where-to-find/

**Comment by microbit-mark** [comment]
requested review from @jaustin for this

**Comment by jaustin** [comment]
Cheers Mark, I like this!
I think perhaps better we link direct to Mailchimp than via eepurl. Also I think we should be consistent on capitalisation: 'DAL, Editors and Devices' seems best
