### ISSUE TITLE
Add direct link to BOM to schematic page

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/dev-docs#120]
Add a direct link to the Bill of Materials https://github.com/bbcmicrobit/hardware/blob/master/400852-Micro%20bit_BOM%20V1.3B.xls to https://tech.microbit.org/hardware/schematic/ based on user feedback

**Comment by microbit-carlos** [comment]
This will be fixed when PR https://github.com/microbit-foundation/dev-docs/pull/386 is merged.
