### ISSUE TITLE
Link to 1.5 hardware/schematic.md

### ISSUE THREAD

**Issue by rosir** [microbit-foundation/dev-docs#125]
Hello,
I did not find the schema of version 1.5.

**Comment by microbit-mark** [comment]
Hi @rosir. Thanks for raising this. This is something we are currently working on and I will update this ticket when we are ready to publish.

**Comment by microbit-mark** [comment]
Hi @rosir Thanks for your patience whilst we made the 1.5 Schematics public. We've now been able to publish them via this Pull Request https://github.com/bbcmicrobit/hardware/pull/6

Specifically, you can find the 1.5 Schematic in this file

https://github.com/bbcmicrobit/hardware/pull/6/files#diff-7679b1d01d33deba2f6555dada1db6dd

I'll keep this issue open until we've added them to the tech site

**Comment by microbit-carlos** [comment]
The public repo is also linked in the https://tech.microbit.org/hardware/schematic/ page, so we can close this issue.
Thanks @rosir for the report!
