### ISSUE TITLE
Basic explanation how this shall work

### ISSUE THREAD

**Issue by StefanL38** [microbit-foundation/dev-docs#133]
## Description
The error is "that thrown into your Github-section I'm completely stumped how this is structured and how it does work."

## Expected behavior
If going to the **MAIN** site of a Github-section finding an **EASY** to understand explanation on how this section works

## Screenshots
not needed words are enough: 
By presenting such a nerdy geeky insider-style of your starting page you scare away all people that would like to contribute in **EASY TO UNDERSTAND DOCUMENTATION**  because even the startpage of how to do that is cryptic and contains **NO** explanations at all. 

If all what you have to answer to me is RTFM of Github - just close this issue and go on nerdying and geekying doing your thing in your isolated insider world

**Comment by microbit-mark** [comment]
Hi @StefanL38. We're always open to suggestions and contributions on how to improve these docs. Is there anything specific you have in mind? For example, what do you understand by the "MAIN site of a Github-section"? Do you mean the README? https://github.com/microbit-foundation/dev-docs/blob/master/README.md
