### ISSUE TITLE
Problème sur Embed Simulator

### ISSUE THREAD

**Issue by SamMas83** [microbit-foundation/dev-docs#140]
Near the 11 juin with the update, there is a bug on the Embed of Simulator.
He always stay on loading and it makes it on all off the genially or Moodle Cours where Simulator Embed are.
Thanks for help

**Comment by microbit-carlos** [comment]
Hi @SamMas83,
I think the issue you are referring has been already been reported in https://github.com/microsoft/pxt-microbit/issues/3276.

I'll close this issue assuming this is the same problem, otherwise if the issue is about https://tech.microbit.org/ please don't hesitate to reopen.
