### ISSUE TITLE
Put live firmware image on tech.microbit.org and developer.mbed.org

### ISSUE THREAD

**Issue by whaleygeek** [microbit-foundation/dev-docs#17]
microbit.org-ticket: 368

We discussed today, the view was we should probably host the live daplink firmware image on developer.mbed.org, and put some notes on tech.microbit.org listing links to all the images and what the key differences are.

**Comment by carlosperate** [comment]
Looks like https://www.mbed.com/en/development/hardware/prototyping-production/daplink/daplink-on-kl26z/ is being maintained up to date. Are we talking about additional images like the micro bit big food survey one?

**Comment by jaustin** [comment]
The latest mbed firmware is now on the official mbed page, so we can close this!
