### ISSUE TITLE
hardware/edgeconnector_ds.md the pinout table in CSV is unavailable

### ISSUE THREAD

**Issue by OwenBrotherwood** [microbit-foundation/dev-docs#18]
Please explain the problem here
http://tech.microbit.org/hardware/edgeconnector_ds/pinmap.csv is not available

---

https://github.com/microbit-foundation/dev-docs/blob/master/hardware/pinmap.csv

**Comment by 04rlowe** [comment]
Which page links to this file? I think http://tech.microbit.org/hardware/edgeconnector_ds/ is the correct reference page for the pin map.

**Comment by OwenBrotherwood** [comment]
Looks like the old issue is fixed
