### ISSUE TITLE
py-ocd description deprecated

### ISSUE THREAD

**Issue by ngammarano** [microbit-foundation/dev-docs#207]
## Description
In the [reading out .hex files (more specifically py-ocd)](https://tech.microbit.org/software/readout_hex/#py-ocd), it says
> * Python 2 (pyOCD is not supported in Python3)

However, in the [README of pyOCD GitHub repository](https://github.com/mbedmicro/pyOCD), it says:
> Requirements
> ------------
> - Python 3.6.0 or later. Currently Python 2.7.9 or later also works, but see note above about Python 2 support being deprecated.

**Comment by microbit-carlos** [comment]
Thanks for the report @ngammarano. You are 100% right, PyOCD has supported Python3 for a little while 🎉 
However, as this section has changed this change is no longer required in the docs:
https://tech.microbit.org/software/hex-format/#reading-out-a-hex-file

Thanks again!
