### ISSUE TITLE
Edge Connector data sheet inconsistencies

### ISSUE THREAD

**Issue by whaleygeek** [microbit-foundation/dev-docs#22]
(3) Notes 1 and 4 are not consistent.

microbit.org-ticket: 541

**Comment by microbit-mark** [comment]
Do we know what isn't consistent here? Not sure what the wording should be @whaleygeek?

**Comment by microbit-mark** [comment]
Closing as I can't work out from the ticket what the issue is and i think the issue is too old to return to the user.
