### ISSUE TITLE
hardware description page acc/mag swapped

### ISSUE THREAD

**Issue by whaleygeek** [microbit-foundation/dev-docs#25]
(6) On the hardware description, the part numbers for the accelerometer and magnetometer are swapped.

microbit.org-ticket: 541

**Comment by 04rlowe** [comment]
I believe this issue has been corrected (?)
![29820180-85b24092-8cbb-11e7-8c78-b2b0d456e1b4](https://user-images.githubusercontent.com/30410608/32406760-63c5c6ee-c176-11e7-9489-1594f450b119.png)

**Comment by itog** [comment]
The description on the image is swapped.
Additionally, the accelerometer IC name is not correct.

<img width="377" alt="screenshot 2018-01-22 16 42 47" src="https://user-images.githubusercontent.com/86078/35209967-b20a1106-ff93-11e7-9830-8b15b90c1f99.png">

**Comment by microbit-mark** [comment]
@jaustin Were the SVGs made in Inkscape? I was hoping to update the images, but can't seem to get it to run on my mac. Can't find an alternative that works either.
