### ISSUE TITLE
Spelling error on hardware page

### ISSUE THREAD

**Issue by whaleygeek** [microbit-foundation/dev-docs#26]
(7) Accelerometer is not spelled Acceleromater.

microbit.org-ticket: 541

**Comment by 04rlowe** [comment]
I believe this issue has been corrected (?)
![29820180-85b24092-8cbb-11e7-8c78-b2b0d456e1b4](https://user-images.githubusercontent.com/30410608/32406785-9f2043c2-c176-11e7-8fac-3b93c76826da.png)

**Comment by repac** [comment]
Confirmed corrected.
