### ISSUE TITLE
Link to Proto-Pic's CAD resources

### ISSUE THREAD

**Issue by jaustin** [microbit-foundation/dev-docs#28]
Ewan has made some nice resources here and we should link to them

https://www.proto-pic.co.uk/micro-bit-resources.html

**Comment by DavidWhaleMEF** [comment]
Should also link to the kitronik CAD resources here:

https://www.kitronik.co.uk/blog/bbc-microbit-cad-resources/

**Comment by microbit-mark** [comment]
Closed by https://github.com/microbit-foundation/dev-docs/pull/52
