### ISSUE TITLE
hardware/schematic.md doesn't actually have a schematic?

### ISSUE THREAD

**Issue by mgrusin** [microbit-foundation/dev-docs#29]
The "Schematics" page (http://tech.microbit.org/hardware/schematic/) doesn't appear to provide an actual schematic for the Microbit. If this is intentional, the page probably shouldn't be called "Schematics." Otherwise, a clearly-labeled link to a PDF of the schematic, along with a link to the source files, would be appreciated. Thank you!

**Comment by whaleygeek** [comment]
Yes, sorry about this. It's on the list.

You can get at the schematics for the reference design here:

http://tech.microbit.org/hardware/reference-design/

https://github.com/microbit-foundation/microbit-reference-design/tree/master/PDF/Schematic%20Print

**Comment by 04rlowe** [comment]
@whaleygeek as per http://tech.microbit.org/hardware/schematic/

> The schematic will be kept in version control in the micro:bit GitHub account. It will be released by the BBC once final sign-off around license terms has completed.

Can this now be updated to provide a link to https://github.com/microbit-foundation/microbit-reference-design/tree/master/PDF/Schematic%20Print ?

**Comment by jaustin** [comment]
We should link to the top level GitHub repo for the hardware:
https://github.com/bbcmicrobit/hardware
