### ISSUE TITLE
microbit daplink mbed page 404

### ISSUE THREAD

**Issue by carlosperate** [microbit-foundation/dev-docs#30]
This link no longer works: https://www.mbed.com/en/development/hardware/prototyping-production/daplink/daplink-on-kl26z/
Google cache: https://webcache.googleusercontent.com/search?q=cache:cWB53FQwfRAJ:https://www.mbed.com/en/development/hardware/prototyping-production/daplink/daplink-on-kl26z/+&cd=1&hl=en&ct=clnk&gl=uk

The link in the documentation is used here: https://github.com/microbit-foundation/dev-docs/blob/4bbb39bf753d61e8700ca4f3d2e1687e64626fb9/software/interface.md#L78

I was also linking to this in a list of micro:bit resources, so it'd be great if we could find an alternative or it's new location if it has been moved.

**Comment by jaustin** [comment]
Thanks for pointing out - It works again now. It was a bug created by the addition of the new link (in order to close a different issue) and the CMS's re-organisation.
