### ISSUE TITLE
Link to the micro:bit picture maker

### ISSUE THREAD

**Issue by jaustin** [microbit-foundation/dev-docs#33]
It lives here
https://pycomic.github.io/microbit.html

**Comment by microbit-mark** [comment]
Where should this live? Under 'Software' as a direct link or a page on creating documentation/reference material for micro:bit?

**Comment by jaustin** [comment]
I think under the Python page maybe? As an additional tool? Also perhaps in the readme.md of dev-docs?

**Comment by microbit-mark** [comment]
Closed by https://github.com/microbit-foundation/dev-docs/pull/71
