### ISSUE TITLE
The V1/V2 toggles don't correctly highlight which table is shown

### ISSUE THREAD

**Issue by JohnVidler** [microbit-foundation/dev-docs#357]
## Description
On [this page](https://tech.microbit.org/hardware/edgeconnector/#pins-and-signals) the V1/V2 switches appear to both toggle the table, but don't update their colour to match which table is shown.

To reproduce, load the page, and repeatedly click either the V1 or V2 buttons, and the table will change, but the highlighted version does not match.

## Expected behaviour
I would expect that either:

1. The V1/V2 buttons act as single toggle, such that repeatedly pressing one of the buttons does not toggle between the two states, but continues to present the clicked version's table.
2. or... that the V1/V2 toggle is represented as a flip/flop button with the correct version highlighted, irrespective which button is pressed.

Personally, I would _much_ prefer option 1, to remove any ambiguity, and to conform best to user expectations.

## Screenshots
<img width="847" alt="image" src="https://user-images.githubusercontent.com/537325/159294555-ec29c975-f125-4d14-b13e-cf42b2100dc2.png">
Note that although V2 is highlighted, this is in fact, the V1 pin table.

**Comment by microbit-carlos** [comment]
@microbit-mark I'd suspect this would also apply to any other page with a similar V1/V2 toggle button.

**Comment by microbit-mark** [comment]
I think this might be the only occurrence. Other pages with separate version info like https://tech.microbit.org/hardware/ and https://tech.microbit.org/hardware/i2c/ are actually links to pages rather than showing and hiding info. 

It's quite confusing. Agreed @JohnVidler, we could just have one button that defaults to V2 info as that is the default for the hardware and i2c pages

**Comment by microbit-carlos** [comment]
> we could just have one button that defaults to V2 info as that is the default for the hardware and i2c pages

Not sure I understood, instead of having a `V1` and `V2` button, just have single one that toggles between V1 and V2?

**Comment by microbit-mark** [comment]
That's what I thought John meant in 1., but on re-reading I think this is just to have the desired experience of each button only showing the table it is associated with. I'll look to fix that.

**Comment by microbit-carlos** [comment]
This can be really confusing (as shown in https://github.com/bbcmicrobit/micropython/issues/773), so it'd be good to fix this in the tech site.

@jaustin @microbit-robert is this something that could be prioritised next for tech side backlog? (so I don't mean to prioritise this over any other work, but to put it at the top of the tech site specific backlog).
