### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by carlosperate** [microbit-foundation/dev-docs#37]
The link to this image is broken: https://developer.mbed.org/media/uploads/JonnyA/600xNxmicrobit_platform_image_2.png.pagespeed.ic.uXq2rT5rpA.png

Can be found in : http://tech.microbit.org/hardware/schematic/
https://github.com/microbit-foundation/dev-docs/blob/4bbb39bf753d61e8700ca4f3d2e1687e64626fb9/hardware/schematic.md

And: http://tech.microbit.org/hardware/edgeconnector/
https://github.com/microbit-foundation/dev-docs/blob/4bbb39bf753d61e8700ca4f3d2e1687e64626fb9/hardware/edgeconnector.md

**Comment by 04rlowe** [comment]
I believe this issue has been corrected (?)
![29820180-85b24092-8cbb-11e7-8c78-b2b0d456e1b4](https://user-images.githubusercontent.com/30410608/32407083-620b03be-c17b-11e7-88c9-ade5c89507b5.png)

**Comment by carlosperate** [comment]
Yes, it was fixed in https://github.com/microbit-foundation/dev-docs/commit/46121b98d18dd1270b32c10868b36ed63840c2f2.
