### ISSUE TITLE
1 sim

### ISSUE THREAD

**Issue by ivans805** [microbit-foundation/dev-docs#401]
Edit as necessary

### Example Project
![Image](https://images.unsplash.com/photo-1552581234-26160f608093?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80){:style="max-width: 50%;"}

**Project abstract:** A brief summary of the project to help people reading this to understand it.

**Level of research:** Masters, Phd, R&D, Conference paper

**Status:** Complete, WIP

**Who is involved:** Organisation/Sponsor, Externals like schools

**What is the area of research:** Computer Science, Eng, Block coding

**Output:** Where has the research surfaced? Links to Github, Blogs, Researchgate etc

**Contact:** Email address/social media handle for people to contact if they are interested in finding out more.

**Comment by microbit-carlos** [comment]
Looks like this might have been opened by accident, so I'll close it.
@ivans805 if that wasn't the case please feel free to create a new issue filling up the sections of the template.
