### ISSUE TITLE
Broken image on edge connector page

### ISSUE THREAD

**Issue by DavidWhaleMEF** [microbit-foundation/dev-docs#42]
url: http://tech.microbit.org/hardware/edgeconnector/

The edge connector diagram has disappeared. It was there when we first released the website back in October 2016.

![screen shot 2017-04-16 at 20 10 09](https://cloud.githubusercontent.com/assets/25079586/25073539/c1819888-22e0-11e7-82f5-d8d05b0b1899.png)

**Comment by carlosperate** [comment]
Already reported ;)
https://github.com/microbit-foundation/dev-docs/issues/37
