### ISSUE TITLE
hardware/schematic.md

### ISSUE THREAD

**Issue by greggjaskiewicz** [microbit-foundation/dev-docs#46]
https://developer.mbed.org/media/uploads/JonnyA/600xNxmicrobit_platform_image_2.png.pagespeed.ic.uXq2rT5rpA.png
 returns 404

**Comment by carlosperate** [comment]
@jaustin Image has been broken for a while (#37, #42), based on the filename I assume it uploaded by you. Is it possible it's this image from https://developer.mbed.org/platforms/Microbit/ :

![microbit](https://developer.mbed.org/media/uploads/JonnyA/microbit_platform_image_2.png)

**Comment by jaustin** [comment]
This has now been fixed and deployed. Thanks for logging it, sorry for the delay in fixing!
