### ISSUE TITLE
Incorrect use of term 'cap touch' in lots of places

### ISSUE THREAD

**Issue by DavidWhaleMEF** [microbit-foundation/dev-docs#48]
This is the source of the original error:

http://www.bbc.co.uk/mediacentre/mediapacks/microbit/specs

But lots of other places on the internet have copied this and got it wrong.

cc @jaustin 

Can we get the BBC to fix this 'error' as it is misleading.

**Comment by DavidWhaleMEF** [comment]
![screen shot 2017-08-19 at 21 24 33](https://user-images.githubusercontent.com/25079586/29489956-33d4023a-8525-11e7-9771-bbff954cd0ef.png)

**Comment by microbit-mark** [comment]
I've searched dev-docs and can't find any further instances of 'cap touch' so closing
