### ISSUE TITLE
Slack form, remove micro:bit Thursdays

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/dev-docs#53]
micro:bit Thursdays on the slack channel is not really happening anymore, so we should remove it from http://tech.microbit.org/get-involved/where-to-find/

**Comment by microbit-mark** [comment]
This is also referenced in our canned responses in FD, so I'll take the action to do both

**Comment by microbit-carlos** [comment]
Great, thanks @microbit-mark!

**Comment by microbit-mark** [comment]
Have made changes here

https://github.com/microbit-foundation/dev-docs/pull/55

**Comment by microbit-carlos** [comment]
Thanks Mark!
