### ISSUE TITLE
Broken "battery advice" link in hardware/powersupply.md 

### ISSUE THREAD

**Issue by cssbz** [microbit-foundation/dev-docs#58]
http://tech.microbit.org/hardware/powersupply/ says "... the BBC provide some advice on the types of batteries that are approved for use with the micro:bit _battery advice_", but unfortunately when I follow the link, I see only information on returning faulty micro:bits.

**Comment by cssbz** [comment]
Perhaps this is the intended link destination - I'm not sure: https://support.microbit.org/support/solutions/articles/19000013982-how-do-i-power-my-micro-bit-

**Comment by microbit-mark** [comment]
@jaustin do we have access to the original BBC files to reproduce the advice here?

**Comment by microbit-mark** [comment]
Closed by https://github.com/microbit-foundation/dev-docs/pull/61
