### ISSUE TITLE
KL26 or KL26Z

### ISSUE THREAD

**Issue by carlosperate** [microbit-foundation/dev-docs#67]
We are refering the interface microcontroller as KL26 or KL26Z, we should probably stick to one.

To be honest, I'm not sure which one is the "correct" one. DAPLink refers to the procressor as a KL26Z, but a google search for "KL26Z" gives mostly results about the FRDM-KL26Z development board. NXP refers to the family as the "Kinetis KL26" (although all parts contain the Z in the format MKL26Zxxxyyyy), so "KL26" is likely to be correct one.

**Comment by microbit-carlos** [comment]
This has been updated overtime and all mentions are now `KL26` 👍
