### ISSUE TITLE
Remove link to mailing list in Slack form

### ISSUE THREAD

**Issue by carlosperate** [microbit-foundation/dev-docs#84]
https://tech.microbit.org/get-involved/where-to-find/

There is a link to the old micro:bit mailing list that has been deleted, so we need to remove this link.

**Comment by microbit-mark** [comment]
closed by https://github.com/microbit-foundation/dev-docs/commit/f9bca975ebe0e3583f6a0df5310106b54fc2d9d4#diff-0f504f00cb03333183490a943524c817

**Comment by carlosperate** [comment]
Great, thanks Mark!
