### ISSUE TITLE
Missing license.txt suggest CC-by-SA

### ISSUE THREAD

**Issue by majikthys** [microbit-foundation/dev-docs#92]
It's unclear what license the assets in this repository fall under, specifically of concern are the diagrams and fritzing in this folder: https://github.com/microbit-foundation/dev-docs/tree/master/hardware/assets

These images are widely republished across the internet and it would be good to add an explicit copyleft license such as creative commons share-alike w/ attribution: https://creativecommons.org/licenses/by-sa/4.0/

**Comment by microbit-mark** [comment]
closed in https://github.com/microbit-foundation/dev-docs/pull/127 🎉 
Thanks for the suggestion @majikthys

**Comment by majikthys** [comment]
Thanks!
